#pragma once

#include "rapidcheck/Gen.h"

namespace rc {
namespace newgen {

//! Generates an STL container containing elements generated by the given
//! generator. For containers that have both keys and values, you need to supply
//! both a key generator and a value generator separately.
template<typename Container, typename ...Ts>
Gen<Container> container(Gen<Ts> ...gens);

} // namespace newgen
} // namespace rc

#include "Container.hpp"
