#pragma once

#include "rapidcheck/Seq.h"
#include "rapidcheck/seq/Create.h"
#include "rapidcheck/seq/Operations.h"
#include "rapidcheck/seq/Transform.h"

#include "rapidcheck/Shrinkable.h"
#include "rapidcheck/shrinkable/Create.h"
#include "rapidcheck/shrinkable/Operations.h"
#include "rapidcheck/shrinkable/Transform.h"

#include "rapidcheck/Gen.h"
#include "rapidcheck/newgen/Arbitrary.h"
#include "rapidcheck/newgen/Container.h"
#include "rapidcheck/newgen/Create.h"
#include "rapidcheck/newgen/Distinct.h"
#include "rapidcheck/newgen/Exec.h"
#include "rapidcheck/newgen/Numeric.h"
#include "rapidcheck/newgen/Select.h"
#include "rapidcheck/newgen/Text.h"
#include "rapidcheck/newgen/Transform.h"
#include "rapidcheck/newgen/Tuple.h"

#include "rapidcheck/Check.h"
#include "rapidcheck/Show.h"
#include "rapidcheck/Assertions.h"

#include "rapidcheck/gen/Collection.h"
#include "rapidcheck/gen/Common.h"
#include "rapidcheck/gen/Distinct.h"
#include "rapidcheck/gen/Element.h"
#include "rapidcheck/gen/Generator.h"
#include "rapidcheck/gen/Invoke.h"
#include "rapidcheck/gen/Numeric.h"
#include "rapidcheck/gen/OneOf.h"
#include "rapidcheck/gen/Parameters.h"
#include "rapidcheck/gen/Text.h"
#include "rapidcheck/gen/Tuple.h"

#include "rapidcheck/arbitrary/Arbitrary.h"
#include "rapidcheck/arbitrary/Collection.h"
#include "rapidcheck/arbitrary/Numeric.h"
#include "rapidcheck/arbitrary/Tuple.h"

#include "rapidcheck/state/State.h"
